### ISSUE TITLE
Check-In [Back-end] (5/20)

### ISSUE THREAD

**Issue by SerenaJewels** [gotechnica/technica-site-2024#5]
This task involves altering the way we set up the DynamoDB registration tables. This year, rather than having two tables, one for registration and one for check-in, we are going to have a toggle in the registration table for whether or not they have checked in. Additionally, we had a few issues last year when people tried to register under that same email, since all hacker information is attached to their email. Instead, we were thinking about changing it to make each hacker's information attached to their name.

If you are new to AWS or using Serverless, I highly recommend watching the AWS and Serverless tutorials listed in the video tutorials section

**To-Do**

- [ ] Creating a check-in criterion for each hacker registered
- [x] Make each hacker's identifying attribute their full name

If you have any questions, feel free to put them in the #tech channel. You got this and good luck!

**Comment by valentina-hong** [comment]
For the first to-do, there's a few tasks to complete when more of the backend is built: 
- In handler.js, whenever we use the email to retrieve something, we should now use both email and first name 
- In the check-in app, we should toggle the check-in field in the registration table
