### ISSUE TITLE
Scanner App [Back-End] (8/18)

### ISSUE THREAD

**Issue by SerenaJewels** [gotechnica/technica-site-2024#73]
This is the beginning of the scanner app! 

This script is for checking people in during the day of hackathon. For now, what we need to do is update the links from last year's to this year's. This will mainly be API-Endpoints and DynamoDB table names. There aren't any changes that we need to implement for this script, so if all goes well, there shouldn't be too many issues getting it to run outside of that!

We do plan on having the scanner on the actual app this year, but in case something happens, we'd like to have a back up.

The general idea of the scanner is that at the beginning of the hackathon, when everyone checks in, we scan a QR code. It'll bring up their general information stored in the DynamoDB table. From there, there should be a button to confirm everything and mark that they've been registered.

**Comment by Kaidriver** [comment]
will change qr code to grab email + first name

**Comment by caramurphyy** [comment]
will update api endpoints
